### ISSUE TITLE
no support Django==4.2

### ISSUE THREAD

**Issue by kitanin90** [juliomalegria/django-chunked-upload#68]
i start django server and get answer:

`Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/vladimir/.pyenv/versions/3.11.2/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/vladimir/.pyenv/versions/3.11.2/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/vladimir/.pyenv/versions/project_name/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/vladimir/.pyenv/versions/project_name/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/Users/vladimir/.pyenv/versions/project_name/lib/python3.11/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Users/vladimir/.pyenv/versions/project_name/lib/python3.11/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/vladimir/.pyenv/versions/project_name/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/vladimir/.pyenv/versions/project_name/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/vladimir/.pyenv/versions/project_name/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/Users/vladimir/.pyenv/versions/project_name/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vladimir/.pyenv/versions/3.11.2/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/vladimir/.pyenv/versions/project_name/lib/python3.11/site-packages/chunked_upload/models.py", line 10, in <module>
    from .constants import CHUNKED_UPLOAD_CHOICES, UPLOADING
  File "/Users/vladimir/.pyenv/versions/project_name/lib/python3.11/site-packages/chunked_upload/constants.py", line 1, in <module>
    from django.utils.translation import ugettext as _
ImportError: cannot import name 'ugettext' from 'django.utils.translation' (/Users/vladimir/.pyenv/versions/project_name/lib/python3.11/site-packages/django/utils/translation/__init__.py)`

**Comment by SaeedRz96** [comment]
With the same error in Django>4, I just added these lines on the top of settings.py, and worked.

```
import django
from django.utils.translation import gettext
django.utils.translation.ugettext = gettext
```

**Comment by JohananOppongAmoateng** [comment]
Closing the  issue a pr for this has been merged
